# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'clean build'
    scheme: 'EssentialFeed'
    sdk: 'macosx'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath


- task: Xcode@5
  inputs:
    actions: 'clean build'
    scheme: 'EssentialFeed'
    sdk: 'iphonesimulator'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
- task: Xcode@5
  inputs:
    actions: 'test'
    sdk: 'macosx'
    scheme: 'CI_macOS'
    xcodeVersion: '13'
    packageApp: false
    publishJUnitResults: true
    testRunTitle: 'CI macOS'
- task: Xcode@5
  inputs:
    actions: 'test'
    sdk: 'iphonesimulator'
    scheme: 'CI_iOS'
    xcodeVersion: '13'
    packageApp: false
    publishJUnitResults: true
    testRunTitle: 'CI iOS'
